module.exports = {
  apps: [
    {
      name: "findvalue-backend",
      script: "./backend/dist/main.js",
      cwd: "./backend",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      log_file: "./backend/logs/combined.log",
      out_file: "./backend/logs/out.log",
      error_file: "./backend/logs/error.log",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      merge_logs: true,
      max_memory_restart: "1G",
      node_args: "--max_old_space_size=1024",
    },
    {
      name: "findvalue-python-service",
      script: "python3",
      args: "main.py",
      cwd: "./python-analysis-service",
      instances: 1,
      exec_mode: "fork",
      interpreter: "python3",
      env: {
        PYTHONPATH: "./python-analysis-service",
        ENV: "production",
      },
      log_file: "./python-analysis-service/logs/combined.log",
      out_file: "./python-analysis-service/logs/out.log",
      error_file: "./python-analysis-service/logs/error.log",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      merge_logs: true,
      max_memory_restart: "2G",
    },
    {
      name: "findvalue-stock-crawler",
      script: "python3",
      args: "main.py",
      cwd: "./stock-crawler",
      instances: 1,
      exec_mode: "fork",
      interpreter: "python3",
      env: {
        PYTHONPATH: "./stock-crawler",
        ENV: "production",
      },
      log_file: "./stock-crawler/logs/combined.log",
      out_file: "./stock-crawler/logs/out.log",
      error_file: "./stock-crawler/logs/error.log",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      merge_logs: true,
      max_memory_restart: "1G",
      cron_restart: "0 */6 * * *", // 每6小时重启一次
    },
  ],
};
